title: Gosaidsno Docs
description: Documentation for the Gosaidsno AOP Library
theme: just-the-docs # for local testing using this otherwise;
#remote_theme: just-the-docs/just-the-docs # make sure we use this when pushing to github

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-github-metadata

# This is crucial for your navigation to work
enable_search_in_sidebar: true

# Cosmetic settings (to make it look cool like Chirpy)
color_scheme: dark
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue

# Just the Docs configuration
aux_links:
  "GitHub":
    - "//github.com/gosaidsno/gosaidsno"
